name: DailyLight
main: de.relulu.DailyLight.DailyInit
version: ${project.version}
api-version: 1.13
author: ReLuLu
commands:
  daily:
    description: Provides access to administrative daily commands and prints an overview of them.
    usage: /daily
    aliases:
  dcheck:
    description: Teleports the player back to the last triggered checkpoint.
    usage: /dcheck
    aliases:
  dstart:
    description: Sets the starting point for a parcours. If used on another player, the current position of the issuer will be used.
    usage: /dstart, /dstart [playername]
    aliases:
  dend:
    description: Ends a parcours. If used on another player, it will end his parcours.
    usage: /dend, /dend [playername]
    aliases: